skn_last_small_project/mainapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views as auth_views
from .                   import views

app_name = 'mainapp'

urlpatterns = [
    path(''         , views.intro, name="intro"),
    path('main/'    , views.main, name="main"),
    path('chat/'    , views.chat, name="chat"),

    path('login/'   , auth_views.LoginView.as_view(template_name="mainapp/login.html"), name="login"),
    path('signup/'  , views.signup, name="signup"),
    path('logout/'  , views.logout, name="logout"),

    path('mypage/'    , views.mypage, name="mypage"),
    path('deregister/', views.deregister, name="deregister"),
]

# 업로드 파일 경로설정
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

skn_last_small_project/skn_last_small_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(''      , include("mainapp.urls")),
]

skn_last_small_project/templates/layout/base_content_only.html
<!doctype html>

{% load static %}

<html lang="ko">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        {# Title 블럭 ##################################################}
        <title>{% block title %}{% endblock title %}</title>

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/global.css' %}">

        {# Upper script 블럭 ###########################################}
        {% block upper_script %}{% endblock upper_script %}
        {# Style 블럭 ##################################################}
        {% block style %}{% endblock style %}
    </head>
    <body>
        <main>
            {# Content 블럭 ##################################################}
            {% block content %}{% endblock %}
        </main>

        {% include "./form_error_toast.html" %}

        {# Bootstrap JS, Popper JS #}
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>

        <script src="{% static 'js/global.js' %}"></script>

        {# Script 블럭 ##################################################}
        {% block script %}{% endblock script %}
    </body>
</html>

skn_last_small_project/templates/layout/base_default.html
<!doctype html>

{% load static %}

<html lang="ko">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        {# Title 블럭 ##################################################}
        <title>{% block title %}{% endblock title %}</title>

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/global.css' %}">

        {# Upper script 블럭 ###########################################}
        {% block upper_script %}{% endblock upper_script %}
        {# Style 블럭 ##################################################}
        {% block style %}{% endblock style %}
    </head>
    <body>
        {% include "./nav.html" %}
        <main>
            {# Content 블럭 ##################################################}
            {% block content %}{% endblock %}
        </main>

        {% include "./form_error_toast.html" %}

        {# Bootstrap JS, Popper JS #}
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>

        <script src="{% static 'js/global.js' %}"></script>

        {# Script 블럭 ##################################################}
        {% block script %}{% endblock script %}
    </body>
</html>

skn_last_small_project/templates/layout/form_error_toast.html
{% if form.errors %}
    <div>
        <!-- Position it: -->
        <!-- - `.toast-container` for spacing between toasts -->
        <!-- - `top-0` & `end-0` to position the toasts in the upper right corner -->
        <!-- - `.p-3` to prevent the toasts from sticking to the edge of the container  -->
        <div class="toast-container top-0 end-0 p-3">
            {% for error in form.non_field_errors %}
                <div class="toast fade show" role="alert" aria-live="assertive" aria-atomic="true">
                    <div class="toast-header text-bg-danger">
{#                        <img src="..." class="rounded me-2" alt="...">#}
                        <strong class="me-auto">Please check.</strong>
                        {#                    <small class="text-body-secondary">just now</small>#}
                        <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
                    </div>
                    <div class="toast-body">
                        {{ error }}
                    </div>
                </div>
            {% endfor %}

            {% for field in form %}
                {% if field.errors %}
                    <div class="toast fade show" role="alert" aria-live="assertive" aria-atomic="true">
                        <div class="toast-header">
{#                            <img src="..." class="rounded me-2" alt="...">#}
                            <strong class="me-auto">Please check '{{ field.label }}'.</strong>
                            {#                    <small class="text-body-secondary">just now</small>#}
                            <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
                        </div>
                        <div class="toast-body">
                            {{ form.errors }}
                        </div>
                    </div>
                {% endif %}
            {% endfor %}

        </div>
    </div>
{% endif %}

skn_last_small_project/templates/layout/loading.html
<style>
    #loading span {
        position: absolute;
        display: block;
        width: 60px;
        height: 60px;
        border: 3px solid aquamarine;
        border-radius: 100%;
    }

    #loading .a,
    #loading .b,
    #loading .c {
        animation-name: rotate;
        animation-iteration-count: infinite;
        animation-timing-function: linear;
    }

    #loading .a {
        animation-duration: 1500ms;
    }

    #loading .b {
        animation-duration: 4500ms;
        transform-origin: 67% 67%;
        width: 40px;
        height: 40px;
    }

    #loading .c {
        animation-duration: 9000ms;
        transform-origin: 81% 81%;
        width: 20px;
        height: 20px;
    }


    @keyframes rotate {
        0% { transform: rotateZ(0deg); }
        100% { transform: rotateZ(360deg); }
    }

    #loadingBox {
        position: absolute;
        top: 123px;
        left: 0;
        width: 100%;
        height: 100%;
        display:none;
        z-index:9;
    }
    #loadingBox.on {
        display:block;
    }

    .center {
        position: absolute;
        margin-top: -123px;
        background-color:rgba(0,0,0,0.7);
        width: 100%;
        height: inherit;
        justify-content: center;
        align-items: center;
        border-radius:10px;
        display:flex;
    }
</style>

<div id="loadingBox">
    <div class="center" id="loading">
    <span class="a">
        <span class="b">
            <span class="c"></span>
        </span>
    </span>
    </div>
</div>

<script>
    const $loading = document.getElementById("loadingBox");
    const startLoading = () => $loading.classList.add("on");
    const stopLoading  = () => $loading.classList.remove("on");
</script>

skn_last_small_project/templates/layout/nav.html
<nav class="navbar navbar-expand-lg bg-body-tertiary" style="background-color: #e3f2fd;" data-bs-theme="light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url "mainapp:main" %}">💪 Gym-PT</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
{#                <li class="nav-item">#}
{#                    <a class="nav-link active" aria-current="page" href="#">Home</a>#}
{#                </li>#}
{#                <li class="nav-item">#}
{#                    <a class="nav-link" href="#">Features</a>#}
{#                </li>#}
{#                <li class="nav-item">#}
{#                    <a class="nav-link" href="#">Pricing</a>#}
{#                </li>#}
            </ul>

            <ul class="navbar-nav mb-2 mb-lg-1">
                {% if user.is_authenticated %}
                    <li class="nav-item me-2">
                        <a class="btn btn-outline-success p-0" href="{% url "mainapp:mypage" %}">
                            <img src="{% if user.member.picture %}{{ user.member.picture.url }}{% else %}/media/profile/default.jpg{% endif %}" alt="Logo" width="37" height="37" class="rounded mx-auto d-block">
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="btn btn-primary" href="{% url "mainapp:logout" %}">Log out</a>
                    </li>
                {% else %}
                    <li class="nav-item me-2">
                        <a class="btn btn-light" href="{% url "mainapp:login" %}">Sign in</a>
                    </li>
                    <li class="nav-item">
                        <a class="btn btn-outline-success" href="{% url "mainapp:signup" %}">Sign up</a>
                    </li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>